language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  global:
    secure: CYSqAOG8DONCHrE58R8JNPH1hOfIz7jZXevBU9i75eSA5pjotoh/0HGWwPwA/AtMOmlTFgPzr9fID84TW3OLaxP+eTwU+IJHNWeX+xPZDBxJOlehnH5+RI5xhudzFR2ccKXlv+/ZMU0AvHQt17qyvy1Eyg80wGdtlYO8deCN9e2RFdRI6e1Ga2mJEO5WIlC96WeQMEXIfr/cp/6ChgVY6ovsQtw1z2Mdqjgh21qflIr+FUMdfY+80RBLp47QA4LwiyeBFjubSMS8FFGGtw7Esc5xqooJQbOE/+It3BR9cg71EAgHrMFX264rbmdxm0Hfvc/M05kiHlUOAW11I0SUBajyOxUf7ce3RKJoJQsROYkGlE7AGRNAdM6PhQqcq+04b5V/rTf9qSo96dymd+hjABE6dfOrPYBOJ28jOrJ1n8kNs8iAlDbIwQFBQN+o75AoPuSKlGhajiQ94oor1ayEbyzA0MDuw0muVrPRlj9M5fOKRWQbvQw2UoexhpGRCHARGlgW2mo27n07CMdV3LAgzG28YoAiSpdGJvdydvPzRNbJI1kG41Ht/usR8YrmYPIH+GTT6Dd/BPq5W8kE8QdctDd6/RL4ea7bOJ9G1ylIlhgk9UzKnOWtp1scj0EmAcC+CG0NadU5OpNyihClPuwap2LQMdodBiJqtTsFwYLXe7A=
